### ISSUE TITLE
Help curl file

### ISSUE THREAD

**Issue by levinhne** [jyggen/curl#16]
It work with files

**Comment by jyggen** [comment]
Hm? What is your problem exactly? The library will support file uploading using CurlFile in the next release, see issue #15 for more information.

**Comment by levinhne** [comment]
i want to use it with $_FILE when image has been uploaded !

**Comment by jyggen** [comment]
Then you should be able to do something like this:

```php
$finfo = new finfo(FILEINFO_MIME_TYPE);
Curl::post('http://example.com/', [
    'file' => new CurlFile($_FILES['upload']['tmp_name'], $finfo->file($_FILES['upload']['tmp_name']), $_FILES['upload']['name']),
]);
```

**Comment by levinhne** [comment]
thank you for support. I will using it in my project
