### ISSUE TITLE
Send Postdata as postfield and not with http_build_query

### ISSUE THREAD

**Issue by tzfrs** [jyggen/curl#20]
Hi,

When doing a post request I want the data to be sent as postfield and not with http_build_query

Example:

This works:

    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, "https://clients6.google.com/rpc");
    curl_setopt($curl, CURLOPT_POST, 1);
    curl_setopt($curl, CURLOPT_POSTFIELDS, '[{"method":"pos.plusones.get","id":"p","params":{"nolog":true,"id":"' . $url . '","source":"widget","userId":"@viewer","groupId":"@self"},"jsonrpc":"2.0","key":"p","apiVersion":"v1"}]');
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-type: application/json'));
    $curl_results = curl_exec ($curl);
    curl_close ($curl);
    $json = json_decode($curl_results, true);
    var_dump($json);

Now using this library

    $requestURI = env('GOOGLE_COUNT_URL') . '?key='. env('GOOGLE_PUBLIC_API_KEY');
    $data       = '[{"method":"pos.plusones.get","id":"p","params":{"nolog":true,"id":"' . $url . '","source":"widget","userId":"@viewer","groupId":"@self"},"jsonrpc":"2.0","key":"p","apiVersion":"v1"}]';
    $response = Curl::post($url, $data); 

This throws the following exception

>ErrorException in Curl.php line 155:
http_build_query(): Parameter 1 expected to be Array or Object. Incorrect value given

When I pass the data as json_decoded array/object I get null as response

    $data       = json_decode('[{"method":"pos.plusones.get","id":"p","params":{"nolog":true,"id":"' . $url . '","source":"widget","userId":"@viewer","groupId":"@self"},"jsonrpc":"2.0","key":"p","apiVersion":"v1"}]');

**Comment by jyggen** [comment]
This should be fixed in the upcoming 4.0 release since the Curl helper class no longer uses `http_build_query()`. Try your code against master and see if it solves your issue.

**Comment by tzfrs** [comment]
Hi, using `"jyggen/curl": "v4.0.0-RC1"` works, however I'm getting an error that I have to set the contenttype. I couldn't find in the documentation how to to add Request headers. How would I do that?

Normally I would do it like this

    $curl = new Curl();
    $response = $curl->setHTTPHeader(['Content-type: application/json'])
                ->post($url, json_encode($parameters));`

How does it work with your class?

**Comment by jyggen** [comment]
The Curl class only allows for basic usage, you need to instantiate a Dispatcher and Request(s) manually if you want more advance control over your requests.

Something like this maybe:

```php
$dispatcher = new Dispatcher();
$request    = new Request('http://example.com');

$request->setOption(CURLOPT_HTTPHEADER, [
    'Content-type: application/json'
]);

$dispatcher->add($request);
$dispatcher->execute();
```
