### ISSUE TITLE
CURLOPT_HEADER protected

### ISSUE THREAD

**Issue by Bananamoon** [jyggen/curl#21]
Hello, I'm trying to make a curl request with your library. Everything works fine except for the fact that I get the header with my response. Since the rest of my response is JSON I can not seem to remove the headers to be able to read my response.

In the Request.php the CURLOPT_HEADER is protected so I can not overwrite it during my curl request. Is there anyway way we can change this with a config file or anything? When I put it on false my curl request works perfectly fine.

Thanks for the help!

**Comment by jyggen** [comment]
`CURLOPT_HEADER` can't be changed because the library uses the headers to create the response object. I don't see why the headers being included in the response would give you issues though, using `$request-> getResponse()->getContent()` should give you your JSON body without the headers, no?
