### ISSUE TITLE
How to get all requests in RAW data?

### ISSUE THREAD

**Issue by Zhenjas** [jyggen/curl#22]
Hello! 

Can i get RAW data from multiple requests?

$allData=Curl::get(array('www.1page.com/jsonData','www.2page.com/jsonData'));

I need all data in RAW(JSON)

Best regards,
Eugene

**Comment by jyggen** [comment]
You should be able to do something like this:

```php
$allData = Curl::get(array('www.1page.com/jsonData','www.2page.com/jsonData'));

foreach ($allData as $response) {
    $rawJson = $response->getContent();
}
```

**Comment by Zhenjas** [comment]
ok, thanks!
