### ISSUE TITLE
CURLOPT_INFILESIZE

### ISSUE THREAD

**Issue by alixaxel** [jyggen/curl#5]
I'm pretty sure that this is wrong:

```
$session->setOption(CURLOPT_INFILESIZE, mb_strlen($data, 'UTF-8'));
```

Shouldn't that be?

```
$session->setOption(CURLOPT_INFILESIZE, strlen($data));
```

**Comment by hyip** [comment]
The following is work for me: 
> $session->setOption(CURLOPT_INFILESIZE, mb_strlen($data, '8bit'));
